type Model {
  _id: String
  parentId: String
  rootProcessId: String
  registryId: String
  name: String
  bpmn: String
  solidity: String,
  policyId: String
  taskRoleId: String
  processes(
    _id: String
  ): [Process]
}
