# The "Mutation" type is the root of all GraphQL mutations.
type Mutation {
  registry: Registry,
  model(
    bpmn: String!
    registry: String!
  ): Model
  policy(
    model: String!
    registry: String!
  ): Policy
}